### PR TITLE
onEnd should return the response from the server

### PR DESCRIPTION
**Pull request by tomhah**
onEnd should return the response from the server, so that you can grab the URL to the saved file etc.

### CODE REVIEW

**Comment by edgesoft** [comment]
@tomhah Great! I just published response from server. I think you are running an old version. the callbackParams are gone. This is the api instead

```
uploadController(this.files, {
          url: '/upload',
          onProgress(event) {
            signals.user.uploadProgress({...event, path: path})
          },
          onEnd(event) {
            signals.user.uploadDone({...event, path: path})
          }
        });
```

So you will have the event percentComplete in onProgress and response in onDone. Also we have supported headers and changed serverParams to query

**Comment by tomhah** [comment]
Awesome! :)

**Comment by edgesoft** [comment]
@tomhah Also we always want callback that we had from calling uploadController.

**Comment by edgesoft** [comment]
@tomhah Are you in need for multiple uploads? Like to add multiple files? They will upload one by one but will be treated as batches instead.

**Comment by tomhah** [comment]
Nah, I only need one file at the moment :-)

**Comment by edgesoft** [comment]
Awesome :)

**Pull request closed without merging**
